# Generated by Django 3.2 on 2021-05-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_comment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
