# Generated by Django 3.2 on 2021-04-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='duraion',
            new_name='duration',
        ),
    ]
